---
- hosts: docker
  gather_facts: no
  tasks:
  - name: "Install Docker dependencies"
    yum:
      name: "{{ item }}"
      state: latest
    loop:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - python2-pip
      - yum-plugin-versionlock
      - docker-compose

  - name: "Add Docker CE repo"
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo

  - name: "Install Docker"
    package:
      name: docker-ce-18.06.1.ce-3.el7
      state: present

  - name: "Lock Docker version"
    command: yum versionlock docker-ce-18.06*
      warn=False

  - name: "Enable and start Docker service"
    systemd:
      name: docker
      state: started
      enabled: yes

  - name: "Install docker PIP dependencies"
    pip:
      name: docker-py
