---
- hosts: all
  gather_facts: no
  tasks:
  - name: "Configure SSH keys"
    authorized_key:
      user: root
      state: present
      key: '{{ item }}'
    with_file:
      - "../../../secrets/ssh/public_keys"

  - name: "Disallow password authentication"
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PasswordAuthentication"
                line="PasswordAuthentication no"
                state=present
    notify: restart-ssh

  - name: "Enable root login with SSH-KEY"
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PermitRootLogin"
                line="PermitRootLogin without-password"
                state=present
    notify: restart-ssh

  handlers:
    - name: restart-ssh
      service: name=sshd state=restarted
