---
- hosts: all
  gather_facts: no
  tasks:
  - name: "Disable SELinux"
    selinux:
      state: disabled

  - name: "Get SELinux status on running system"
    command: getenforce
    ignore_errors: true
    register: selinux_status

  - name: "Reboot server if required"
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    ignore_errors: true
    when: '"Permissive" in selinux_status.stdout'

  - name: "Waiting for server to come back"
    local_action: wait_for host={{ ansible_host }} state=started port=22 delay=30
    when: '"Permissive" in selinux_status.stdout'
