---
- hosts: all
  gather_facts: no
  vars:
    TIMEZONE: "{{ lookup('env','TIMEZONE') }}"
  tasks:
  - name: "Install ntp"
    yum:
      name: ntp
      state: latest

  - name: "Enable system services"
    systemd:
      name: ntpd
      state: started
      enabled: yes

  - name: "Set timezone"
    timezone:
      name: {{ TIMEZONE }}
